import {getRadarCache,setRadarCache} from '../core/storage.js?v=11.4.2';
let map=null,marker=null,radar=null,frames=[],frameIndex=0,timer=null,host='https://tilecache.rainviewer.com';
const API='https://api.rainviewer.com/public/weather-maps.json';
export async function initWeatherMap(id,lat,lon){const el=document.getElementById(id);if(!el)return false;if(!window.L){el.innerHTML='<div class="map-fallback"><strong>Map unavailable</strong><span>The map library could not be loaded. Weather data is still working.</span></div>';return false}try{if(!map){map=L.map(el,{zoomControl:false,attributionControl:true}).setView([lat,lon],9);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);marker=L.circleMarker([lat,lon],{radius:7,color:'#fff',weight:2,fillColor:'#5fa8ff',fillOpacity:1}).addTo(map)}else{map.setView([lat,lon],9);marker.setLatLng([lat,lon]);map.invalidateSize()}return await loadRadar()}catch{el.innerHTML='<div class="map-fallback"><strong>Map unavailable</strong><span>RainCheck could not initialize the interactive map.</span></div>';return false}}
export async function loadRadar(){try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();host=d.host||host;frames=d.radar?.past||[];setRadarCache({host,frames,at:Date.now()});frameIndex=Math.max(0,frames.length-1);showFrame();return frames.length}catch{const cached=getRadarCache();if(cached){host=cached.host||host;frames=cached.frames||[];frameIndex=Math.max(0,frames.length-1);showFrame();return frames.length}document.dispatchEvent(new CustomEvent('raincheck:radarUnavailable'));return 0}}
function showFrame(){if(!map||!frames.length)return;const f=frames[frameIndex];const url=`${host}${f.path}/256/{z}/{x}/{y}/2/1_1.png`;if(radar)map.removeLayer(radar);radar=L.tileLayer(url,{opacity:.62,zIndex:20,maxZoom:7}).addTo(map);document.dispatchEvent(new CustomEvent('raincheck:radarframe',{detail:{index:frameIndex,total:frames.length,time:f.time}}))}
export function radarStep(dir=1){if(!frames.length)return;frameIndex=(frameIndex+dir+frames.length)%frames.length;showFrame()}
export function radarSeek(index=0){if(!frames.length)return;frameIndex=Math.max(0,Math.min(frames.length-1,Number(index)||0));showFrame()}
export function radarPlay(){if(timer||!frames.length)return;timer=setInterval(()=>radarStep(1),800);document.dispatchEvent(new CustomEvent('raincheck:radarplay',{detail:true}))}
export function radarPause(){clearInterval(timer);timer=null;document.dispatchEvent(new CustomEvent('raincheck:radarplay',{detail:false}))}
export function radarToggle(){timer?radarPause():radarPlay()}
export function radarState(){return{index:frameIndex,total:frames.length,playing:!!timer,time:frames[frameIndex]?.time||null}}
