import {weatherInfo} from '../core/config.js?v=11.4.2';
import {getRainWindow,bestOutdoorWindow,buildAlerts,briefing,activityAdvice,detectAnomalies,dayScore} from '../features/intelligence.js?v=11.4.2';
import {nextHours,trendSvg,forecastStats} from '../features/forecast.js?v=11.4.2';
import {dayTimeline} from '../features/timeline.js?v=11.4.2';
import {planDay} from '../features/planner.js?v=11.4.2';
import {getPlaces,getHistory} from '../core/storage.js?v=11.4.2';
export const $=s=>document.querySelector(s);export const $$=s=>[...document.querySelectorAll(s)];
export const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
export const fmtTemp=(v,u='metric')=>v==null?'—':`${Math.round(u==='metric'?v:v*9/5+32)}°`;export const fmtSpeed=(v,u='metric')=>v==null?'—':`${Math.round(u==='metric'?v:v*.621371)} ${u==='metric'?'km/h':'mph'}`;export const fmtTime=v=>new Date(v).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});export const direction=d=>['N','NE','E','SE','S','SW','W','NW'][Math.round((Number(d)||0)/45)%8];
export function renderAll(state){
 const d=state.weather,c=d?.current;if(!c)throw new Error('Weather response did not contain current conditions');const info=weatherInfo(c.weather_code),u=state.settings.unit;
 document.body.dataset.weather=info[0].toLowerCase().replaceAll(' ','-');document.body.dataset.day=c.is_day?'day':'night';
 $('#weatherContent').classList.remove('hidden');$('#emptyState').classList.add('hidden');
 $('#currentCity').textContent=state.place.name;$('#currentCountry').textContent=[state.place.admin,state.place.country].filter(Boolean).join(', ');$('#currentDate').textContent=new Date(c.time).toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'});
 $('#currentTemp').textContent=fmtTemp(c.temperature_2m,u);$('#currentWeatherIcon').innerHTML=`<i class="fas fa-${info[2]}"></i>`;$('#weatherMain').textContent=info[0];$('#weatherDescription').textContent=info[1];
 $('#feelsLike').textContent=fmtTemp(c.apparent_temperature,u);$('#feelsLikeDetail').textContent=fmtTemp(c.apparent_temperature,u);$('#tempMax').textContent=fmtTemp(d.daily.temperature_2m_max?.[0],u);$('#tempMin').textContent=fmtTemp(d.daily.temperature_2m_min?.[0],u);$('#windSpeed').textContent=fmtSpeed(c.wind_speed_10m,u);
 $('#humidity').textContent=c.relative_humidity_2m==null?'—':`${Math.round(c.relative_humidity_2m)}%`;$('#visibility').textContent=visibility(state.weather);$('#pressure').textContent=c.surface_pressure==null?'—':`${Math.round(c.surface_pressure)} hPa`;$('#uvIndex').textContent=String(Math.round(d.daily.uv_index_max?.[0]??0));$('#windGust').textContent=fmtSpeed(c.wind_gusts_10m,u);$('#windDirection').textContent=direction(c.wind_direction_10m);$('#dewPoint').textContent=fmtTemp(c.dew_point_2m,u);$('#lastUpdated').textContent=state.offline?'Offline · cached forecast':`Updated ${fmtTime(Date.now())}`;$('#dataState').textContent=state.offline?'Cached':'Live';$('#versionLabel').textContent=`V${state.version?.split('.')[0]||10}`;
 renderHero(state);renderHourly(state);renderTimeline(state);renderDaily(state);renderRain(state);renderAlerts(state);renderSun(state);renderWind(state);renderAQI(state);renderHistory(state);if(state.history?.daily)renderHistoricalChart(state);renderActivities(state);renderTrends(state);renderPlanner(state);renderAnomalies(state);renderPlaces(state);renderSettings(state);
}
const visibility=data=>{const v=data.current?.visibility??data.hourly?.visibility?.find(x=>x!=null);return v==null?'—':`${(v/1000).toFixed(1)} km`};
function renderHero(state){const rain=getRainWindow(state.weather),best=bestOutdoorWindow(state.weather);$('#heroSummary').textContent=briefing(state.weather,state.place);$('#rainCheckTitle').textContent=rain?'Rain is on the way':'Mostly dry ahead';$('#rainCheckText').textContent=rain?`Peak chance ${rain.probability}% around ${fmtTime(rain.start)}.`:'No significant rain signal in the near-term forecast.';$('#rainCheckMeta').textContent=rain?`${rain.amount.toFixed(1)} mm expected · about ${rain.duration} min`:'Umbrella not currently necessary';$('#bestWindow').textContent=best?`Best outdoor window · ${fmtTime(best.time)} · ${fmtTemp(best.temp,state.settings.unit)} · ${best.prob}% rain`:''}
function renderHourly(state){const h=nextHours(state.weather,18);$('#hourlyForecast').innerHTML=h.map((x,i)=>`<div class="hour ${i===0?'selected':''}"><span>${i===0?'Now':fmtTime(x.time)}</span><i class="fas fa-${weatherInfo(x.code)[2]}"></i><strong>${fmtTemp(x.temp,state.settings.unit)}</strong><small>${x.rain}%</small></div>`).join('')||'<div class="empty">Hourly forecast unavailable.</div>'}function renderTimeline(state){
 const periods=dayTimeline(state.weather);
 const icons={sunrise:'sun',sun:'sun',moon:'moon'};
 $('#dayTimeline').innerHTML=periods.length?periods.map(x=>`<article class="timeline-card"><div class="timeline-icon"><i class="fas fa-${icons[x.icon]||'cloud-sun'}"></i></div><div class="timeline-copy"><strong>${safe(x.label)}</strong><span>${safe(x.condition)} · ${fmtTemp(x.temp,state.settings.unit)}</span><small>${x.rain}% rain · wind ${fmtSpeed(x.wind,state.settings.unit)}${x.precip>0?` · ${x.precip.toFixed(1)} mm`:''}</small></div></article>`).join(''):'<div class="empty">Today’s timeline is unavailable.</div>';
 const rain=Math.max(...periods.map(x=>x.rain),0);
 $('#timelineSummary').textContent=periods.length?`${rain}% peak rain chance today`:'Forecast unavailable';
}
function renderDaily(state){const d=state.weather.daily,s=forecastStats(state.weather);$('#forecastContainer').innerHTML=d.time.slice(0,10).map((t,i)=>`<div class="day"><div><strong>${i===0?'Today':new Date(t).toLocaleDateString([],{weekday:'short'})}</strong><small>${new Date(t).toLocaleDateString([],{month:'short',day:'numeric'})}</small></div><i class="fas fa-${weatherInfo(d.weather_code[i])[2]}"></i><span class="rain-pill">${d.precipitation_probability_max[i]??0}%</span><strong>${fmtTemp(d.temperature_2m_max[i],state.settings.unit)}</strong><span class="low">${fmtTemp(d.temperature_2m_min[i],state.settings.unit)}</span></div>`).join('');$('#forecastStats').textContent=`10 days · ${s.wet} wetter days · ${fmtTemp(s.min,state.settings.unit)}–${fmtTemp(s.max,state.settings.unit)}`}
function renderRain(state){const h=nextHours(state.weather,12);$('#rainChanceContainer').innerHTML=`<div class="rain-bars">${h.map(x=>`<div class="rain-col"><b>${x.rain}%</b><div><i style="height:${Math.max(5,x.rain)}%"></i></div><small>${fmtTime(x.time)}</small></div>`).join('')}</div>`}
function renderAlerts(state){const a=buildAlerts(state.weather,state.settings);$('#weatherAlerts').innerHTML=a.map(x=>`<article class="alert ${x.level}"><i class="fas fa-${x.icon}"></i><div><strong>${safe(x.title)}</strong><span>${safe(x.text)}</span></div></article>`).join('');$('#alertCount').textContent=`${a.length} ${a.length===1?'insight':'insights'}`}
function renderSun(state){const d=state.weather.daily,c=state.weather.current,sr=new Date(d.sunrise[0]).getTime(),ss=new Date(d.sunset[0]).getTime(),now=new Date(c.time).getTime(),pct=Math.max(0,Math.min(100,(now-sr)/(ss-sr)*100));$('#sunTrack').style.setProperty('--sun-position',`${pct}%`);$('#sunrise').textContent=fmtTime(d.sunrise[0]);$('#sunset').textContent=fmtTime(d.sunset[0]);$('#daylightDuration').textContent=`${Math.max(0,Math.round((ss-sr)/3600000))}h daylight`}
function beaufort(k){const ms=(k||0)/3.6,names=['Calm','Light air','Light breeze','Gentle breeze','Moderate breeze','Fresh breeze','Strong breeze','Near gale','Gale','Strong gale','Storm','Violent storm','Hurricane'];return names[Math.min(12,Math.floor((ms+1.625)/1.25))]}
function renderWind(state){const c=state.weather.current,u=state.settings.unit;$('#windCompass').innerHTML=`<div class="wind-card"><div class="compass"><span class="north">N</span><span class="east">E</span><span class="south">S</span><span class="west">W</span><div class="compass-ring"><i class="fas fa-location-arrow" style="transform:rotate(${Number(c.wind_direction_10m)||0}deg)"></i></div><strong>${direction(c.wind_direction_10m)}</strong></div><div class="wind-readout"><div><span>Speed</span><strong>${fmtSpeed(c.wind_speed_10m,u)}</strong></div><div><span>Gusts</span><strong>${fmtSpeed(c.wind_gusts_10m,u)}</strong></div><div><span>Direction</span><strong>${Math.round(c.wind_direction_10m||0)}° · ${direction(c.wind_direction_10m)}</strong></div><div><span>Beaufort</span><strong>${beaufort(c.wind_speed_10m)}</strong></div></div></div>`}
function renderAQI(state){const h=state.air?.hourly;if(!h){$('#aqiContainer').innerHTML='<div class="empty">Air quality is temporarily unavailable.</div>';return}let idx=(h.time||[]).findIndex(t=>new Date(t).getTime()>=Date.now()-3600000);if(idx<0)idx=0;const a=h.us_aqi?.[idx]??0,label=a<=50?'Good':a<=100?'Moderate':a<=150?'Sensitive groups':a<=200?'Unhealthy':'Very unhealthy',pct=Math.min(100,a/2);$('#aqiContainer').innerHTML=`<div class="aqi-head"><div><span class="eyebrow">US AQI</span><strong>${Math.round(a)}</strong><b class="aqi-label">${label}</b></div><div class="aqi-gauge" style="--aqi:${pct}%"></div></div><p>${a<=50?'Air quality is clean for normal outdoor activity.':a<=100?'Acceptable air quality for most people.':'Sensitive people may want to limit prolonged outdoor exertion.'}</p><div class="pollutants"><span>PM2.5 <b>${Math.round(h.pm2_5?.[idx]??0)} µg/m³</b></span><span>PM10 <b>${Math.round(h.pm10?.[idx]??0)} µg/m³</b></span><span>NO₂ <b>${Math.round(h.nitrogen_dioxide?.[idx]??0)} µg/m³</b></span><span>O₃ <b>${Math.round(h.ozone?.[idx]??0)} µg/m³</b></span></div>`}
function renderActivities(state){$('#activityGrid').innerHTML=activityAdvice(state.weather,state.settings.activityMode).map(a=>`<article class="activity"><i class="fas fa-${a[2]}"></i><div><strong>${safe(a[0])}</strong><span>${safe(a[1])}</span></div></article>`).join('')}
function renderTrends(state){$('#temperatureTrend').innerHTML=trendSvg(state.weather,'temperature');$('#windTrend').innerHTML=trendSvg(state.weather,'wind');$('#rainTrend').innerHTML=trendSvg(state.weather,'rain')}
function renderAnomalies(state){const a=detectAnomalies(state.weather);$('#anomalyList').innerHTML=a.length?a.map(x=>`<div class="anomaly"><i class="fas fa-circle-info"></i><div><strong>${safe(x.title)}</strong><span>${safe(x.text)}</span></div></div>`).join(''):'<div class="empty">No unusual forecast patterns detected.</div>'}
function renderPlanner(state){const p=planDay(state.weather,state.settings.commuteMinutes);$('#commuteAdvice').innerHTML=`<strong>${safe(p.commute.title)}</strong><span>${safe(p.commute.text)}</span>`;$('#plannerOutdoor').textContent=p.best?`${fmtTime(p.best.time)} · ${fmtTemp(p.best.temp,state.settings.unit)} · ${p.best.prob}% rain`:'No clear window';$('#dayScore').textContent=p.score;$('#scoreLabel').textContent=p.score>=80?'Good day':p.score>=60?'Mixed day':'Challenging day'}
function renderHistory(state){const items=getHistory(state.place.lat,state.place.lon);if(!items.length){$('#weatherHistory').innerHTML='<div class="empty">RainCheck will build a local trend as you use it.</div>';return}const min=Math.min(...items.map(x=>x.temp)),max=Math.max(...items.map(x=>x.temp)),range=Math.max(1,max-min);$('#weatherHistory').innerHTML=`<div class="history-chart">${items.slice().reverse().map(x=>`<div class="history-point"><b>${Math.round(x.temp)}°</b><i style="height:${22+((x.temp-min)/range)*95}px"></i><small>${new Date(x.time).toLocaleTimeString([],{hour:'numeric'})}</small></div>`).join('')}</div><small>Local observations · ${items.length} points</small>`}
function renderHistoricalChart(state){const d=state.history?.daily;if(!d?.time?.length)return;const highs=d.temperature_2m_max||[],lows=d.temperature_2m_min||[],means=d.temperature_2m_mean||[],rain=d.precipitation_sum||[],wind=d.wind_speed_10m_max||[];const min=Math.min(...lows),max=Math.max(...highs),range=Math.max(1,max-min);const u=state.settings.unit;$('#historicalChart').innerHTML=d.time.slice(0,7).map((t,i)=>{const hi=highs[i]??means[i]??0,lo=lows[i]??means[i]??hi,mean=means[i]??((hi+lo)/2),h=Math.max(16,((hi-min)/range)*100),l=Math.max(8,((lo-min)/range)*100);return `<article class="history-day"><div class="history-head"><span class="history-label">${new Date(t).toLocaleDateString([],{weekday:'short'})}</span><strong class="history-high">${fmtTemp(hi,u)}</strong></div><div class="history-track"><i class="history-range" style="height:${Math.max(22,h-l)}%;margin-bottom:${Math.min(70,l)}%"></i></div><div><div class="history-low">${fmtTemp(lo,u)} · avg ${fmtTemp(mean,u)}</div><div class="history-rain">${Number(rain[i]??0).toFixed(1)} mm · ${Math.round(wind[i]??0)} km/h</div></div></article>`}).join('');const avg=means.length?means.reduce((a,b)=>a+(b||0),0)/means.length:0;const totalRain=rain.reduce((a,b)=>a+(b||0),0);const maxWind=Math.max(...wind,0);$('#historicalStats').innerHTML=`<div class="history-stat"><span>Average temperature</span><strong>${fmtTemp(avg,u)}</strong></div><div class="history-stat"><span>Total precipitation</span><strong>${totalRain.toFixed(1)} mm</strong></div><div class="history-stat"><span>Peak wind</span><strong>${Math.round(maxWind)} km/h</strong></div>`}
function renderPlaces(state){const list=getPlaces();$('#placesList').innerHTML=list.length?list.map(p=>`<button class="place-row" data-place="${safe(p.id)}"><i class="fas fa-location-dot"></i><span><strong>${safe(p.name)}</strong><small>${safe([p.admin,p.country].filter(Boolean).join(', '))}</small></span><em>${p.temp!=null?fmtTemp(p.temp,state.settings.unit):''}</em><b data-remove="${safe(p.id)}" aria-label="Remove place">×</b></button>`).join(''):'<div class="empty">No saved places yet.</div>';$('#defaultPlaceSelect').innerHTML='<option value="">Automatic</option>'+list.map(p=>`<option value="${safe(p.id)}" ${p.id===state.settings.defaultPlaceId?'selected':''}>${safe(p.name)}</option>`).join('')}
function renderSettings(state){$('#settingsCelsius').classList.toggle('active',state.settings.unit==='metric');$('#settingsFahrenheit').classList.toggle('active',state.settings.unit==='imperial');$('#reducedMotionToggle').checked=state.settings.reducedMotion;$('#notificationBtn').textContent=('Notification'in window&&Notification.permission==='granted')?'Enabled':'Enable';$('#activityMode').value=state.settings.activityMode;$('#travelMinutes').value=state.settings.commuteMinutes;$('#morningBriefingToggle').checked=state.settings.morningBriefing;$('#eveningBriefingToggle').checked=state.settings.eveningBriefing;$('#rainThreshold').value=state.settings.notificationRainChance;$('#heatThreshold').value=state.settings.notificationHeat;$('#windThreshold').value=state.settings.notificationWind;$('#radarAutoplayToggle').checked=state.settings.radarAutoplay;$('#scheduledBriefingToggle').checked=state.settings.scheduledBriefing;$('#performanceMode').value=state.settings.performanceMode||'auto';$$('input[name="theme"]').forEach(r=>r.checked=r.value===state.settings.theme)}
